version: '3.5'
services:
  serverless:
    build:
      context: ./serverless
      args:
        - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    tty: true
    stdin_open: true
    working_dir: /src
    volumes:
      - ./src:/src